version: '2.1'
services:
  school-network-mysql:
    container_name: school-mysql
    image: 'mysql/mysql-server:5.7'
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: school
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3301:3306'
    restart: always
  school-app:
    image: school-spring-boot-app
    build:
      context: ./spring-boot-app
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - /data/school-spring-boot-app
      - ./logs:/app/logs
    depends_on:
      school-network-mysql:
        condition: service_healthy

